FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS base
LABEL author="Alexander Pajer"
WORKDIR /app

FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /src

COPY ["*.csproj", "."]
RUN dotnet restore "ContainerTest.csproj"
COPY . .
RUN dotnet build "ContainerTest.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "ContainerTest.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "ContainerTest.dll"]

# Build Image
# docker build --rm -f "dockerfile" -t containertest .

# Run Image
# docker run -it --rm -p 5051:80 containertest

# Browse using: 
# http://localhost:5051

# Publish Image to dockerhub
# docker tag containertest arambazamba/containertest
# docker push arambazamba/containertest