apiVersion: apps/v1
kind: Deployment
metadata:
  name: skillsapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skillsapi
  template:
    metadata:
      labels:
        app: skillsapi                 
    spec:
      containers:
      - name: skillsapi
        image: arambazamba/skillsapi
        imagePullPolicy: Always
        ports:
        - containerPort: 80        
        resources:
          limits:            
            cpu: "500m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: skillsapi
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 80
  selector:
    app: skillsapi
---
