apiVersion: apps/v1
kind: Deployment
metadata:
  name: skillsui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skillsui
  template:
    metadata:
      labels:
        app: skillsui                 
    spec:
      containers:
      - name: skillsui
        image: arambazamba/skillsui
        imagePullPolicy: Always
        ports:
        - containerPort: 80        
        resources:
          limits:            
            cpu: "500m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: skillsui
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 80
  selector:
    app: skillsui
---
